### ISSUE TITLE
How can I improve the spanish translation?

### ISSUE THREAD

**Issue by aldobelus0** [MarkusWME/phpBB---Auto-Drafts#2]
Hi. The spanish translation left the situation like that:

![sin nombre](https://cloud.githubusercontent.com/assets/15985449/26494514/4c6150bc-421f-11e7-8ae7-71ac3c8b2d9d.jpg)
Only a part of the drafts name are translated, so, how can I translate this two buttons? There's a way to do it by making a modification at an archive? I use to do this with Filezilla. 

If you can tell me, please, which archive should be the appropriate one, please, I happily could do the change...

The phpBB version is 3.2.0. My operative system, Manjaro GNU/Linux with KDE.

**Comment by MarkusWME** [comment]
Hi!

Which release of the extension do you use? It seems to me like the one you are using doesn't contain the spanish translations. The latest release of the extension can be downloaded [here](https://github.com/MarkusWME/phpBB---Auto-Drafts/releases/download/v1.1.3/autodrafts-1.1.3.zip "v1.1.3"). This version also contains the newest spanish translation. With this version it should work correctly.

**Comment by aldobelus0** [comment]
I have downloading from here, the same place where I'm writing now, and the same place where you can read "update spanish and add turkish translation" at the extension. You can watch it at the capture... 

![borradoresforo](https://cloud.githubusercontent.com/assets/15985449/26514445/39a27926-4272-11e7-9888-83b026301cfc.png)

So, if you say that I have to install another one and that one it's different from this one, I should trust you... But I think you should say it where the extension is placed. I had only followed the instructions...

**Comment by aldobelus0** [comment]
And no, I had installed the last version and still is doing what I asked... The very same thing...

**Comment by MarkusWME** [comment]
Which locale do you have selected? Is there an alternative one to _es_? The extension currently only supports _es_. I don't know if there are any "dialects". Maybe this could be a reason.

**Comment by aldobelus0** [comment]
es, from spanish, is what I want. I don't know if there are any dialects, either. 

But, where can I select a language? The only place to configure the drafts is this one:

![borradores](https://cloud.githubusercontent.com/assets/15985449/26524238/e3b7e68e-432c-11e7-941c-63219b3866d3.png)

There is no place to configure an "es" language, and nevertheless a "dialect"! (And I don't care, either!).

**Comment by MarkusWME** [comment]
The language in which the texts are shown will be selected by phpBB automatically from the logged in users settings. If phpBB can't find a language pack for the extension it will backup to the default language. So it seems like the _es_ folder doesn't exist on your forum (because the rest is spanish as I can see). So please have a look if all of the files you can see [here](https://github.com/MarkusWME/phpBB---Auto-Drafts/tree/master/pcgf/autodrafts/language/es) exist in the folder _ext/pcgf/autodrafts/language/es_ beginning from the root path of your forum. If not, you simply have to create all needed folders and download those files into it.

**Comment by aldobelus0** [comment]
They are, and were, there!! 

(This is Filezilla, just in case it's unrecognisable for you with this theme).

![borradores](https://cloud.githubusercontent.com/assets/15985449/26531328/2c32f038-43e7-11e7-80a0-ba102e75d167.png)

**Comment by MarkusWME** [comment]
OK. So I looked at the language packs of phpBB. There are two language packs available: _es_ and _es_x_tu_. I also tried what happens when you have the second one selected and only installed the _es_ language pack of the extension. It seems like exactly this is the problem. So if you have installed [Spanish (Casual Honorifics)](https://www.phpbb.com/customise/db/translation/spanish_casual_honorifics/) it may cause this issue. To solve it you can simply copy the _es_ folder of the extension and rename it to _es_x_tu_. When doing that you have support for both of this language packs.

Hope this helps.

**Comment by aldobelus0** [comment]
I have had problems with the forum. In a bit I'll come back

**Comment by aldobelus0** [comment]
I'm sorry. I said I will be back in a few moments and passed more than a year... I finally left **PHP BB** forums and I forgot. 

It happened that, a few times, the installation crashed or didn't recognised my password. This strange behaviour happened a lot of times. This forced me to do a few installations and, at last, I get bored and quite to use this forum type.

Thank you, @MarkusWME, for your help.
